#!/bin/bash

echo "🚀 Applying Funect Sales Pipeline Database Migration..."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/tmlydufhzyaegbsbuzlg/editor"
echo ""
echo "2. Click 'SQL Editor' in the left sidebar"
echo ""
echo "3. Click '+ New query'"
echo ""
echo "4. Copy the ENTIRE contents of: supabase/migrations/001_initial_schema.sql"
echo ""
echo "5. Paste into the SQL Editor"
echo ""
echo "6. Click 'Run' or press Cmd/Ctrl + Enter"
echo ""
echo "7. You should see: 'Success. No rows returned'"
echo ""
echo "8. Verify by going to Table Editor - you should see 7 tables:"
echo "   - users"
echo "   - prospects"
echo "   - contacts"
echo "   - activities"
echo "   - offers"
echo "   - tags"
echo "   - prospect_tags"
echo ""
echo "✅ Migration complete!"
